/* SPDX-License-Identifier: GPLv3-or-later */

#ifndef TOKEN_H
#define TOKEN_H

typedef enum TokenType_s
{
	TOKEN_NONE,
	TOKEN_UNKNOWN,
	TOKEN_EOF,
	TOKEN_NUMBER,
	TOKEN_IDENTIFIER,
	TOKEN_KEYWORD,
	TOKEN_MULTIPLY,
	TOKEN_DIVIDE,
	TOKEN_ADD,
	TOKEN_SUBTRACT,
	TOKEN_LESS,
	TOKEN_GREATER,
	TOKEN_GE,
	TOKEN_LE,
	TOKEN_EQUAL,
	TOKEN_ASSIGN,
	TOKEN_STRING,
	TOKEN_NEWLINE,
	TOKEN_ARITHMETIC_OPERATORS_BEGIN = TOKEN_MULTIPLY,
	TOKEN_ARITHMETIC_OPERATORS_END = TOKEN_EQUAL,
	TOKEN_COMPARISON_OPERATORS_BEGIN = TOKEN_LESS,
	TOKEN_COMPARISON_OPERATORS_END = TOKEN_ASSIGN,
} TokenType;

typedef struct Token_s
{
	TokenType type;
	char *text;
} Token;

#endif // TOKEN_H
